import type { Metadata } from "next";

import { LegalPage } from "../_components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service — Billion",
};

const LAST_UPDATED = "August 31, 2026";

const SECTIONS = [
  {
    title: "1. Acceptance of Terms",
    body: "By accessing our website, joining our waitlist, or downloading and using the Billion application ('the App'), you agree to be bound by these Terms of Service. If you do not agree, do not use our services.",
  },
  {
    title: "2. Description of Service",
    body: "Billion provides AI-generated summaries and analyses of publicly available government documents, together with civic and election information compiled from public and third-party sources, for informational and civic-education purposes only. This is not legal, financial, or professional advice. Always verify information through the primary sources we link to.",
  },
  {
    title: "3. Eligibility",
    body: "You must be at least 13 years of age to use our services. If you are under 18, you represent that you have obtained parental or guardian consent.",
  },
  {
    title: "4. Prohibited Conduct",
    body: "You agree not to: (a) reverse-engineer or decompile any part of the App; (b) interfere with or disrupt our infrastructure; (c) scrape or harvest data using automated means; or (d) use the App to distribute misleading or unlawful content.",
  },
  {
    title: "5. Intellectual Property",
    body: "All original content, design, and software are the property of Billion and protected by applicable intellectual property laws. Government documents are in the public domain. You receive a limited, non-exclusive, non-transferable license for personal, non-commercial use only.",
  },
  {
    title: "6. AI-Generated Content Disclaimer",
    body: "Summaries and other automated content are generated by AI and may contain errors or omissions. Election and ballot information is compiled from government and third-party sources and may be incomplete or out of date. Billion is not liable for decisions made in reliance on this content — always confirm details with official sources before relying on them.",
  },
  {
    title: "7. Disclaimer of Warranties",
    body: "THE APP IS PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.",
  },
  {
    title: "8. Limitation of Liability",
    body: "TO THE FULLEST EXTENT PERMITTED BY LAW, BILLION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF OUR SERVICES.",
  },
  {
    title: "9. Governing Law",
    body: "These Terms are governed by the laws of the State of California, without regard to conflict-of-law principles.",
  },
  {
    title: "10. Changes to These Terms",
    body: "We may update these Terms from time to time. When we do, we will revise the 'Last updated' date shown above, and where we have your contact information (for example, if you joined our waitlist) we may notify you by email. Your continued use of our services after an update takes effect constitutes acceptance of the revised Terms.",
  },
  {
    title: "11. Contact",
    body: "Questions about these Terms? Email us at thatxliner@gmail.com.",
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      lastUpdated={LAST_UPDATED}
      sections={SECTIONS}
      crossLinkHref="/privacy"
      crossLinkLabel="Privacy Policy"
    />
  );
}
