import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

import {
  publishedMeasureRelationships,
  relationshipEvidenceHash,
} from "@acme/api/lib/measure-relationships";
import { measureRelationshipSchema } from "@acme/validators";

import { validateRelationshipCorpus } from "./measure-relationship-generation.js";

/** Register separately reviewed revisions; never approves generated explanations. */
export async function registerRelationshipRevisions(
  corpusValue: unknown,
  values: unknown[],
  directory: string,
) {
  const corpus = validateRelationshipCorpus(corpusValue);
  const drafts = values.map((value) => measureRelationshipSchema.parse(value));
  for (const draft of drafts) {
    if (
      publishedMeasureRelationships(
        corpus.guide,
        draft.measures[0].number,
        corpus.sources.map((s) => ({ url: s.url, hash: s.documentHash })),
        [draft],
      ).length !== 1
    )
      throw new Error(
        `Revision ${draft.revision} is not approved against this capture`,
      );
  }
  await mkdir(directory, { recursive: true });
  for (const draft of drafts) {
    const name = `revision-${relationshipEvidenceHash(draft)}.json`;
    const path = join(directory, name);
    try {
      await writeFile(path, JSON.stringify({ draft }, null, 2) + "\n", {
        flag: "wx",
      });
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      if (
        JSON.stringify(JSON.parse(await readFile(path, "utf8")).draft) !==
        JSON.stringify(draft)
      )
        throw new Error(
          "An immutable revision already exists with different review metadata",
        );
    }
  }
  const files = (await readdir(directory))
    .filter((name) => /^[a-zA-Z0-9-]+\.json$/.test(name))
    .sort();
  const revisions = [];
  for (const file of files) {
    const value = JSON.parse(await readFile(join(directory, file), "utf8"));
    revisions.push({
      file,
      draft: measureRelationshipSchema.parse(value.draft),
    });
  }
  // Latest editorial review wins for an unchanged pair; source gates still apply on every read.
  revisions.sort((a, b) =>
    (b.draft.review.reviewedAt ?? "").localeCompare(
      a.draft.review.reviewedAt ?? "",
    ),
  );
  const registry =
    "// Generated by the relationship register command. Do not edit by hand.\n" +
    revisions
      .map((r, i) => `import revision${i} from "./${r.file}";`)
      .join("\n") +
    `\nexport const relationshipRevisions: readonly unknown[] = [${revisions.map((_, i) => `revision${i}.draft`).join(", ")}];\n`;
  await writeFile(join(directory, "registry.ts"), registry);
  return drafts.length;
}
