import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import { writeEnvValues } from "./files";

void test("marks a newly created value file as generated and secret", () => {
  const directory = mkdtempSync(join(tmpdir(), "billion-env-"));
  const path = join(directory, ".env");
  try {
    writeEnvValues(path, { POSTGRES_URL: "postgres://localhost/db" });
    const contents = readFileSync(path, "utf8");
    assert.match(contents, /^# THIS FILE WAS GENERATED BY `pnpm env:setup`\./);
    assert.match(contents, /Do not commit it/);
    assert.match(contents, /POSTGRES_URL="postgres:\/\/localhost\/db"/);
  } finally {
    rmSync(directory, { recursive: true, force: true });
  }
});
